name: run emscripten

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure CMake with Emscripten
        run: |
          emcmake cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: |
          cmake --build build --config Release

      - name: Prepare Pages Artifact
        run: |
          mkdir -p public
          cp build/AlgoVisualizer_wasm.js public/
          cp build/AlgoVisualizer_wasm.wasm public/
          cp index.html public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
